### ISSUE TITLE
Translate dialog not entirely visible on screen

### ISSUE THREAD

**Issue by sankaritan** [kitt-browser/translate#18] opened 2015-07-27 11:36 UTC
How to reproduce:
- Install latest version of translate into Kitt 1.3.5
- Open some website not in english. Tested with article from idnes.cz or canadiens.nhl.com (french version)
- select some text and press Translate
- translate dialog is not shown entirely (see screen). Only after user presses "tab" icon and then select same tab dialog is shown in its full size. Related also to https://github.com/kitt-browser/translate/issues/17

![file jul 27 1 33 58 pm](https://cloud.githubusercontent.com/assets/6403413/8905001/6cb88990-3464-11e5-9c79-975848ac64ce.png)

**Comment by dedecej** [comment] 2015-08-27 12:20
Caused by improper autolayout and fixed in Kitt.

**Closed as completed by dedecej** 2015-08-27 12:20 UTC
Labels: bug
